spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/currencydb
    username: currencyuser
    password: letstry
  jms:
    template:
      default-destination: RU-DS-EDUCATION-CBR-REQUEST
      receive-timeout: 10